import { useMutation } from '@tanstack/react-query'
import { useState } from 'react'
import { createCampaignContact, createCampaignNote, createCampaignTask, deleteCampaignContact, deleteCampaignNote, deleteCampaignTask, getCampaign, updateCampaignTask } from '#/lib/api/client'

export function CampaignTracking({ campaign, campaignId, refresh }: { campaign: Awaited<ReturnType<typeof getCampaign>>; campaignId: string; refresh: () => Promise<unknown> }) {
  const [task, setTask] = useState(''); const [deadline, setDeadline] = useState(''); const [note, setNote] = useState('')
  const [name, setName] = useState(''); const [role, setRole] = useState(''); const [channel, setChannel] = useState('')
  const action = useMutation({ mutationFn: async (run: () => Promise<unknown>) => run(), onSuccess: () => { void refresh() } })
  return <section className="campaign-tracking" aria-labelledby="tracking-title">
    <div className="campaign-section-heading"><div><p className="eyebrow">Follow-through</p><h2 id="tracking-title">Campaign activity</h2></div><p className="small-copy muted-copy">Private, owner-only tracking</p></div>
    <div className="campaign-tracking-grid">
      <div className="campaign-tracker"><h3>Tasks</h3><form onSubmit={e => { e.preventDefault(); action.mutate(() => createCampaignTask(campaignId, { title: task, deadline: deadline ? new Date(`${deadline}T12:00:00`).toISOString() : null }).then(() => { setTask(''); setDeadline('') })) }}><label>Next action<input required maxLength={240} value={task} onChange={e => setTask(e.target.value)} /></label><label>Deadline (optional)<input type="date" value={deadline} onChange={e => setDeadline(e.target.value)} /></label><button disabled={action.isPending}>Add task</button></form><ul>{campaign.tasks.map(item => <li key={item.id}><label><input type="checkbox" checked={item.completed} onChange={() => action.mutate(() => updateCampaignTask(campaignId, item.id, !item.completed))} /><span>{item.title}{item.deadline ? ` · ${formatDate(item.deadline)}` : ''}</span></label><button aria-label={`Delete task ${item.title}`} onClick={() => action.mutate(() => deleteCampaignTask(campaignId, item.id))}>Delete</button></li>)}</ul></div>
      <div className="campaign-tracker"><h3>Notes</h3><form onSubmit={e => { e.preventDefault(); action.mutate(() => createCampaignNote(campaignId, note).then(() => setNote(''))) }}><label>Private note<textarea required maxLength={5000} value={note} onChange={e => setNote(e.target.value)} /></label><button disabled={action.isPending}>Add note</button></form><ul>{campaign.notes.map(item => <li key={item.id}><span>{item.text}</span><button aria-label="Delete note" onClick={() => action.mutate(() => deleteCampaignNote(campaignId, item.id))}>Delete</button></li>)}</ul></div>
      <div className="campaign-tracker"><h3>Contacts</h3><form onSubmit={e => { e.preventDefault(); action.mutate(() => createCampaignContact(campaignId, { name, role: role || null, channel: channel || null }).then(() => { setName(''); setRole(''); setChannel('') })) }}><label>Name<input required maxLength={200} value={name} onChange={e => setName(e.target.value)} /></label><label>Role<input maxLength={200} value={role} onChange={e => setRole(e.target.value)} /></label><label>Channel<input maxLength={200} value={channel} onChange={e => setChannel(e.target.value)} /></label><button disabled={action.isPending}>Add contact</button></form><ul>{campaign.contacts.map(item => <li key={item.id}><span><strong>{item.name}</strong>{[item.role, item.channel].filter(Boolean).map(value => ` · ${value}`).join('')}</span><button aria-label={`Delete contact ${item.name}`} onClick={() => action.mutate(() => deleteCampaignContact(campaignId, item.id))}>Delete</button></li>)}</ul></div>
      <div className="campaign-tracker campaign-timeline"><h3>Timeline</h3><ol>{campaign.events.map(event => <li key={event.id}><span>{eventLabel(event.event_type)}</span><small>{event.provenance === 'system' ? 'System' : 'You'} · {formatDate(event.created_at)}</small></li>)}</ol></div>
    </div>{action.isError ? <p role="alert" className="campaign-error">The campaign update could not be saved.</p> : null}
  </section>
}

function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) }
function eventLabel(value: string) { return value.replaceAll('_', ' ').replace(/^./, char => char.toUpperCase()) }
