import { useMutation } from '@tanstack/react-query'
import { useState } from 'react'
import { createCampaignContact, createCampaignNote, createCampaignTask, deleteCampaignContact, deleteCampaignNote, deleteCampaignTask, getCampaign, updateCampaignTask } from '#/lib/api/client'

export function CampaignTracking({ campaign, campaignId, refresh, onRequestDelete }: { campaign: Awaited<ReturnType<typeof getCampaign>>; campaignId: string; refresh: () => Promise<unknown>; onRequestDelete: () => void }) {
  const [task, setTask] = useState(''); const [deadline, setDeadline] = useState(''); const [note, setNote] = useState('')
  const [name, setName] = useState(''); const [role, setRole] = useState(''); const [channel, setChannel] = useState('')
  const [openSnapshotId, setOpenSnapshotId] = useState<string | null>(null)
  const [openConfirmationId, setOpenConfirmationId] = useState<string | null>(null)
  const action = useMutation({ mutationFn: async (run: () => Promise<unknown>) => run(), onSuccess: () => { void refresh() } })
  return <section className="campaign-tracking" aria-labelledby="tracking-title">
    <div className="campaign-section-heading"><div><p className="eyebrow">Follow-through</p><h2 id="tracking-title">Campaign activity</h2></div><p className="small-copy muted-copy">Private, owner-only tracking</p></div>
    <div className="campaign-tracking-grid">
      <div className="campaign-tracker"><h3>Tasks</h3><form onSubmit={e => { e.preventDefault(); action.mutate(() => createCampaignTask(campaignId, { title: task, deadline: deadline ? new Date(`${deadline}T12:00:00`).toISOString() : null }).then(() => { setTask(''); setDeadline('') })) }}><label>Next action<input required maxLength={240} value={task} onChange={e => setTask(e.target.value)} /></label><label>Deadline (optional)<input type="date" value={deadline} onChange={e => setDeadline(e.target.value)} /></label><button disabled={action.isPending}>Add task</button></form><ul>{campaign.tasks.map(item => <li key={item.id}><label><input type="checkbox" checked={item.completed} onChange={() => action.mutate(() => updateCampaignTask(campaignId, item.id, !item.completed))} /><span>{item.title}{item.deadline ? ` · ${formatDate(item.deadline)}` : ''}</span></label><button aria-label={`Delete task ${item.title}`} onClick={() => action.mutate(() => deleteCampaignTask(campaignId, item.id))}>Delete</button></li>)}</ul></div>
      <div className="campaign-tracker"><h3>Notes</h3><form onSubmit={e => { e.preventDefault(); action.mutate(() => createCampaignNote(campaignId, note).then(() => setNote(''))) }}><label>Private note<textarea required maxLength={5000} value={note} onChange={e => setNote(e.target.value)} /></label><button disabled={action.isPending}>Add note</button></form><ul>{campaign.notes.map(item => <li key={item.id}><span>{item.text}</span><button aria-label="Delete note" onClick={() => action.mutate(() => deleteCampaignNote(campaignId, item.id))}>Delete</button></li>)}</ul></div>
      <div className="campaign-tracker"><h3>Contacts</h3><form onSubmit={e => { e.preventDefault(); action.mutate(() => createCampaignContact(campaignId, { name, role: role || null, channel: channel || null }).then(() => { setName(''); setRole(''); setChannel('') })) }}><label>Name<input required maxLength={200} value={name} onChange={e => setName(e.target.value)} /></label><label>Role<input maxLength={200} value={role} onChange={e => setRole(e.target.value)} /></label><label>Channel<input maxLength={200} value={channel} onChange={e => setChannel(e.target.value)} /></label><button disabled={action.isPending}>Add contact</button></form><ul>{campaign.contacts.map(item => <li key={item.id}><span><strong>{item.name}</strong>{[item.role, item.channel].filter(Boolean).map(value => ` · ${value}`).join('')}</span><button aria-label={`Delete contact ${item.name}`} onClick={() => action.mutate(() => deleteCampaignContact(campaignId, item.id))}>Delete</button></li>)}</ul></div>
      <div className="campaign-tracker campaign-timeline"><h3>Timeline</h3><ol>{campaign.events.map(event => <li key={event.id}><span>{event.event_type === 'submission_snapshot_created' && typeof event.details.snapshot_id === 'string' ? <button type="button" onClick={() => setOpenSnapshotId(event.details.snapshot_id as string)}>View submitted application</button> : event.event_type === 'submission_confirmed' && typeof event.details.submission_record_id === 'string' ? <button type="button" onClick={() => setOpenConfirmationId(event.details.submission_record_id as string)}>View submission confirmation</button> : eventLabel(event.event_type)}</span><small>{event.provenance === 'system' ? 'System' : 'You'} · {formatDate(event.created_at)}</small></li>)}</ol></div>
      <div className="campaign-tracker campaign-snapshots"><h3>Submitted versions</h3>{campaign.submission_snapshots.length ? campaign.submission_snapshots.map(snapshot => <details id={`snapshot-${snapshot.id}`} key={snapshot.id} open={openSnapshotId === snapshot.id} onToggle={event => setOpenSnapshotId(event.currentTarget.open ? snapshot.id : null)}><summary>Application sent {formatDate(snapshot.created_at)}</summary><SnapshotContent content={snapshot.content} digest={snapshot.content_sha256} /></details>) : <p className="small-copy muted-copy">No submitted application snapshot yet.</p>}</div>
      <div className="campaign-tracker campaign-confirmations"><h3>Submission confirmations</h3>{campaign.submission_confirmations.length ? <>{campaign.submission_confirmations.map(confirmation => <details id={`submission-confirmation-${confirmation.record_id}`} key={confirmation.record_id} open={openConfirmationId === confirmation.record_id} onToggle={event => setOpenConfirmationId(event.currentTarget.open ? confirmation.record_id : null)}><summary>Confirmed {formatDate(confirmation.submitted_at)}</summary><div className="campaign-confirmation-content"><p><strong>Source confirmation</strong> {confirmation.source_confirmation_id}</p><p><strong>Contract</strong> {confirmation.contract_version}</p><h4>Submitted fields</h4><dl>{Object.entries(confirmation.submitted_fields).map(([field, value]) => <div key={field}><dt>{field.replaceAll('_', ' ')}</dt><dd>{typeof value === 'string' ? value : JSON.stringify(value)}</dd></div>)}</dl><a href={`#approval-snapshot-${confirmation.snapshot.id}`}>View exact approved packet snapshot</a><details id={`approval-snapshot-${confirmation.snapshot.id}`}><summary>Exact approved packet snapshot</summary><pre>{JSON.stringify(confirmation.snapshot.content, null, 2)}</pre><small>SHA-256 {confirmation.snapshot.content_sha256}</small></details><p className="small-copy muted-copy">{confirmation.product_copy_deletion_notice}</p></div></details>)}<button type="button" className="campaign-delete-data" onClick={onRequestDelete}>Delete campaign data</button></> : <p className="small-copy muted-copy">No automated submission confirmation yet.</p>}</div>
    </div>{action.isError ? <p role="alert" className="campaign-error">The campaign update could not be saved.</p> : null}
  </section>
}

function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) }
function eventLabel(value: string) { return value.replaceAll('_', ' ').replace(/^./, char => char.toUpperCase()) }
function SnapshotContent({ content, digest }: { content: Record<string, unknown>; digest: string }) { const listing = content.listing as { title?: string; company?: string; description?: string } | null; const cv = content.cv_variant as { name?: string; sections?: unknown[] } | null; const cover = content.cover_letter as { label?: string; result_payload?: unknown } | null; return <div className="campaign-snapshot-content"><p><strong>Listing</strong> {listing ? `${listing.title} · ${listing.company}` : 'Not selected'}</p>{listing?.description ? <p>{listing.description}</p> : null}<p><strong>CV</strong> {cv?.name || 'Not selected'}</p>{cv ? <pre>{JSON.stringify(cv.sections, null, 2)}</pre> : null}<p><strong>Cover letter</strong> {cover?.label || 'Not selected'}</p>{cover ? <pre>{JSON.stringify(cover.result_payload, null, 2)}</pre> : null}<small>SHA-256 {digest}</small></div> }
