/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobMatchRouteImport } from './routes/job-match'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRunsRouteImport } from './routes/admin/runs'
import { Route as ResumeResultHistoryIdRouteImport } from './routes/resume_.result.$historyId'
import { Route as PortfolioResultHistoryIdRouteImport } from './routes/portfolio_.result.$historyId'
import { Route as JobMatchResultHistoryIdRouteImport } from './routes/job-match_.result.$historyId'
import { Route as InterviewResultHistoryIdRouteImport } from './routes/interview_.result.$historyId'
import { Route as CoverLetterResultHistoryIdRouteImport } from './routes/cover-letter_.result.$historyId'
import { Route as CareerResultHistoryIdRouteImport } from './routes/career_.result.$historyId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchRoute = JobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRunsRoute = AdminRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AdminRoute,
} as any)
const ResumeResultHistoryIdRoute = ResumeResultHistoryIdRouteImport.update({
  id: '/resume_/result/$historyId',
  path: '/resume/result/$historyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioResultHistoryIdRoute =
  PortfolioResultHistoryIdRouteImport.update({
    id: '/portfolio_/result/$historyId',
    path: '/portfolio/result/$historyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobMatchResultHistoryIdRoute = JobMatchResultHistoryIdRouteImport.update({
  id: '/job-match_/result/$historyId',
  path: '/job-match/result/$historyId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewResultHistoryIdRoute =
  InterviewResultHistoryIdRouteImport.update({
    id: '/interview_/result/$historyId',
    path: '/interview/result/$historyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoverLetterResultHistoryIdRoute =
  CoverLetterResultHistoryIdRouteImport.update({
    id: '/cover-letter_/result/$historyId',
    path: '/cover-letter/result/$historyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerResultHistoryIdRoute = CareerResultHistoryIdRouteImport.update({
  id: '/career_/result/$historyId',
  path: '/career/result/$historyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/career': typeof CareerRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/job-match': typeof JobMatchRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/career/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/career': typeof CareerRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/job-match': typeof JobMatchRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/career/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/career': typeof CareerRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/job-match': typeof JobMatchRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/career_/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter_/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview_/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match_/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio_/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume_/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/login'
    | '/portfolio'
    | '/reset-password'
    | '/resume'
    | '/settings'
    | '/admin/runs'
    | '/admin/users'
    | '/auth/callback'
    | '/admin/'
    | '/career/result/$historyId'
    | '/cover-letter/result/$historyId'
    | '/interview/result/$historyId'
    | '/job-match/result/$historyId'
    | '/portfolio/result/$historyId'
    | '/resume/result/$historyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/login'
    | '/portfolio'
    | '/reset-password'
    | '/resume'
    | '/settings'
    | '/admin/runs'
    | '/admin/users'
    | '/auth/callback'
    | '/admin'
    | '/career/result/$historyId'
    | '/cover-letter/result/$historyId'
    | '/interview/result/$historyId'
    | '/job-match/result/$historyId'
    | '/portfolio/result/$historyId'
    | '/resume/result/$historyId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/login'
    | '/portfolio'
    | '/reset-password'
    | '/resume'
    | '/settings'
    | '/admin/runs'
    | '/admin/users'
    | '/auth/callback'
    | '/admin/'
    | '/career_/result/$historyId'
    | '/cover-letter_/result/$historyId'
    | '/interview_/result/$historyId'
    | '/job-match_/result/$historyId'
    | '/portfolio_/result/$historyId'
    | '/resume_/result/$historyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareerRoute: typeof CareerRoute
  CoverLetterRoute: typeof CoverLetterRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  InterviewRoute: typeof InterviewRoute
  JobMatchRoute: typeof JobMatchRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CareerResultHistoryIdRoute: typeof CareerResultHistoryIdRoute
  CoverLetterResultHistoryIdRoute: typeof CoverLetterResultHistoryIdRoute
  InterviewResultHistoryIdRoute: typeof InterviewResultHistoryIdRoute
  JobMatchResultHistoryIdRoute: typeof JobMatchResultHistoryIdRoute
  PortfolioResultHistoryIdRoute: typeof PortfolioResultHistoryIdRoute
  ResumeResultHistoryIdRoute: typeof ResumeResultHistoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-match': {
      id: '/job-match'
      path: '/job-match'
      fullPath: '/job-match'
      preLoaderRoute: typeof JobMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/runs': {
      id: '/admin/runs'
      path: '/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminRunsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resume_/result/$historyId': {
      id: '/resume_/result/$historyId'
      path: '/resume/result/$historyId'
      fullPath: '/resume/result/$historyId'
      preLoaderRoute: typeof ResumeResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/result/$historyId': {
      id: '/portfolio_/result/$historyId'
      path: '/portfolio/result/$historyId'
      fullPath: '/portfolio/result/$historyId'
      preLoaderRoute: typeof PortfolioResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-match_/result/$historyId': {
      id: '/job-match_/result/$historyId'
      path: '/job-match/result/$historyId'
      fullPath: '/job-match/result/$historyId'
      preLoaderRoute: typeof JobMatchResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview_/result/$historyId': {
      id: '/interview_/result/$historyId'
      path: '/interview/result/$historyId'
      fullPath: '/interview/result/$historyId'
      preLoaderRoute: typeof InterviewResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter_/result/$historyId': {
      id: '/cover-letter_/result/$historyId'
      path: '/cover-letter/result/$historyId'
      fullPath: '/cover-letter/result/$historyId'
      preLoaderRoute: typeof CoverLetterResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career_/result/$historyId': {
      id: '/career_/result/$historyId'
      path: '/career/result/$historyId'
      fullPath: '/career/result/$historyId'
      preLoaderRoute: typeof CareerResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminRunsRoute: typeof AdminRunsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRunsRoute: AdminRunsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CareerRoute: CareerRoute,
  CoverLetterRoute: CoverLetterRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  InterviewRoute: InterviewRoute,
  JobMatchRoute: JobMatchRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CareerResultHistoryIdRoute: CareerResultHistoryIdRoute,
  CoverLetterResultHistoryIdRoute: CoverLetterResultHistoryIdRoute,
  InterviewResultHistoryIdRoute: InterviewResultHistoryIdRoute,
  JobMatchResultHistoryIdRoute: JobMatchResultHistoryIdRoute,
  PortfolioResultHistoryIdRoute: PortfolioResultHistoryIdRoute,
  ResumeResultHistoryIdRoute: ResumeResultHistoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
