/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingToolsRouteImport } from './routes/landing-tools'
import { Route as LandingExperimentRouteImport } from './routes/landing-experiment'
import { Route as LandingClassicRouteImport } from './routes/landing-classic'
import { Route as JobMatchRouteImport } from './routes/job-match'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumePreviewRouteImport } from './routes/resume_.preview'
import { Route as PortfolioPreviewRouteImport } from './routes/portfolio_.preview'
import { Route as JobMatchPreviewRouteImport } from './routes/job-match_.preview'
import { Route as InterviewPreviewRouteImport } from './routes/interview_.preview'
import { Route as CoverLetterPreviewRouteImport } from './routes/cover-letter_.preview'
import { Route as CareerPreviewRouteImport } from './routes/career_.preview'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ResumeResultHistoryIdRouteImport } from './routes/resume_.result.$historyId'
import { Route as PortfolioResultHistoryIdRouteImport } from './routes/portfolio_.result.$historyId'
import { Route as JobMatchResultHistoryIdRouteImport } from './routes/job-match_.result.$historyId'
import { Route as InterviewResultHistoryIdRouteImport } from './routes/interview_.result.$historyId'
import { Route as CoverLetterResultHistoryIdRouteImport } from './routes/cover-letter_.result.$historyId'
import { Route as CareerResultHistoryIdRouteImport } from './routes/career_.result.$historyId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingToolsRoute = LandingToolsRouteImport.update({
  id: '/landing-tools',
  path: '/landing-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingExperimentRoute = LandingExperimentRouteImport.update({
  id: '/landing-experiment',
  path: '/landing-experiment',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingClassicRoute = LandingClassicRouteImport.update({
  id: '/landing-classic',
  path: '/landing-classic',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchRoute = JobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumePreviewRoute = ResumePreviewRouteImport.update({
  id: '/resume_/preview',
  path: '/resume/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioPreviewRoute = PortfolioPreviewRouteImport.update({
  id: '/portfolio_/preview',
  path: '/portfolio/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchPreviewRoute = JobMatchPreviewRouteImport.update({
  id: '/job-match_/preview',
  path: '/job-match/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPreviewRoute = InterviewPreviewRouteImport.update({
  id: '/interview_/preview',
  path: '/interview/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterPreviewRoute = CoverLetterPreviewRouteImport.update({
  id: '/cover-letter_/preview',
  path: '/cover-letter/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerPreviewRoute = CareerPreviewRouteImport.update({
  id: '/career_/preview',
  path: '/career/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeResultHistoryIdRoute = ResumeResultHistoryIdRouteImport.update({
  id: '/resume_/result/$historyId',
  path: '/resume/result/$historyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioResultHistoryIdRoute =
  PortfolioResultHistoryIdRouteImport.update({
    id: '/portfolio_/result/$historyId',
    path: '/portfolio/result/$historyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobMatchResultHistoryIdRoute = JobMatchResultHistoryIdRouteImport.update({
  id: '/job-match_/result/$historyId',
  path: '/job-match/result/$historyId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewResultHistoryIdRoute =
  InterviewResultHistoryIdRouteImport.update({
    id: '/interview_/result/$historyId',
    path: '/interview/result/$historyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoverLetterResultHistoryIdRoute =
  CoverLetterResultHistoryIdRouteImport.update({
    id: '/cover-letter_/result/$historyId',
    path: '/cover-letter/result/$historyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerResultHistoryIdRoute = CareerResultHistoryIdRouteImport.update({
  id: '/career_/result/$historyId',
  path: '/career/result/$historyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/career': typeof CareerRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/job-match': typeof JobMatchRoute
  '/landing-classic': typeof LandingClassicRoute
  '/landing-experiment': typeof LandingExperimentRoute
  '/landing-tools': typeof LandingToolsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/career/preview': typeof CareerPreviewRoute
  '/cover-letter/preview': typeof CoverLetterPreviewRoute
  '/interview/preview': typeof InterviewPreviewRoute
  '/job-match/preview': typeof JobMatchPreviewRoute
  '/portfolio/preview': typeof PortfolioPreviewRoute
  '/resume/preview': typeof ResumePreviewRoute
  '/career/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/career': typeof CareerRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/job-match': typeof JobMatchRoute
  '/landing-classic': typeof LandingClassicRoute
  '/landing-experiment': typeof LandingExperimentRoute
  '/landing-tools': typeof LandingToolsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/career/preview': typeof CareerPreviewRoute
  '/cover-letter/preview': typeof CoverLetterPreviewRoute
  '/interview/preview': typeof InterviewPreviewRoute
  '/job-match/preview': typeof JobMatchPreviewRoute
  '/portfolio/preview': typeof PortfolioPreviewRoute
  '/resume/preview': typeof ResumePreviewRoute
  '/career/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/career': typeof CareerRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/job-match': typeof JobMatchRoute
  '/landing-classic': typeof LandingClassicRoute
  '/landing-experiment': typeof LandingExperimentRoute
  '/landing-tools': typeof LandingToolsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/career_/preview': typeof CareerPreviewRoute
  '/cover-letter_/preview': typeof CoverLetterPreviewRoute
  '/interview_/preview': typeof InterviewPreviewRoute
  '/job-match_/preview': typeof JobMatchPreviewRoute
  '/portfolio_/preview': typeof PortfolioPreviewRoute
  '/resume_/preview': typeof ResumePreviewRoute
  '/career_/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter_/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview_/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match_/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio_/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume_/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/landing-classic'
    | '/landing-experiment'
    | '/landing-tools'
    | '/login'
    | '/portfolio'
    | '/resume'
    | '/settings'
    | '/auth/callback'
    | '/career/preview'
    | '/cover-letter/preview'
    | '/interview/preview'
    | '/job-match/preview'
    | '/portfolio/preview'
    | '/resume/preview'
    | '/career/result/$historyId'
    | '/cover-letter/result/$historyId'
    | '/interview/result/$historyId'
    | '/job-match/result/$historyId'
    | '/portfolio/result/$historyId'
    | '/resume/result/$historyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/landing-classic'
    | '/landing-experiment'
    | '/landing-tools'
    | '/login'
    | '/portfolio'
    | '/resume'
    | '/settings'
    | '/auth/callback'
    | '/career/preview'
    | '/cover-letter/preview'
    | '/interview/preview'
    | '/job-match/preview'
    | '/portfolio/preview'
    | '/resume/preview'
    | '/career/result/$historyId'
    | '/cover-letter/result/$historyId'
    | '/interview/result/$historyId'
    | '/job-match/result/$historyId'
    | '/portfolio/result/$historyId'
    | '/resume/result/$historyId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/landing-classic'
    | '/landing-experiment'
    | '/landing-tools'
    | '/login'
    | '/portfolio'
    | '/resume'
    | '/settings'
    | '/auth/callback'
    | '/career_/preview'
    | '/cover-letter_/preview'
    | '/interview_/preview'
    | '/job-match_/preview'
    | '/portfolio_/preview'
    | '/resume_/preview'
    | '/career_/result/$historyId'
    | '/cover-letter_/result/$historyId'
    | '/interview_/result/$historyId'
    | '/job-match_/result/$historyId'
    | '/portfolio_/result/$historyId'
    | '/resume_/result/$historyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CareerRoute: typeof CareerRoute
  CoverLetterRoute: typeof CoverLetterRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  InterviewRoute: typeof InterviewRoute
  JobMatchRoute: typeof JobMatchRoute
  LandingClassicRoute: typeof LandingClassicRoute
  LandingExperimentRoute: typeof LandingExperimentRoute
  LandingToolsRoute: typeof LandingToolsRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CareerPreviewRoute: typeof CareerPreviewRoute
  CoverLetterPreviewRoute: typeof CoverLetterPreviewRoute
  InterviewPreviewRoute: typeof InterviewPreviewRoute
  JobMatchPreviewRoute: typeof JobMatchPreviewRoute
  PortfolioPreviewRoute: typeof PortfolioPreviewRoute
  ResumePreviewRoute: typeof ResumePreviewRoute
  CareerResultHistoryIdRoute: typeof CareerResultHistoryIdRoute
  CoverLetterResultHistoryIdRoute: typeof CoverLetterResultHistoryIdRoute
  InterviewResultHistoryIdRoute: typeof InterviewResultHistoryIdRoute
  JobMatchResultHistoryIdRoute: typeof JobMatchResultHistoryIdRoute
  PortfolioResultHistoryIdRoute: typeof PortfolioResultHistoryIdRoute
  ResumeResultHistoryIdRoute: typeof ResumeResultHistoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-tools': {
      id: '/landing-tools'
      path: '/landing-tools'
      fullPath: '/landing-tools'
      preLoaderRoute: typeof LandingToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-experiment': {
      id: '/landing-experiment'
      path: '/landing-experiment'
      fullPath: '/landing-experiment'
      preLoaderRoute: typeof LandingExperimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-classic': {
      id: '/landing-classic'
      path: '/landing-classic'
      fullPath: '/landing-classic'
      preLoaderRoute: typeof LandingClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-match': {
      id: '/job-match'
      path: '/job-match'
      fullPath: '/job-match'
      preLoaderRoute: typeof JobMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume_/preview': {
      id: '/resume_/preview'
      path: '/resume/preview'
      fullPath: '/resume/preview'
      preLoaderRoute: typeof ResumePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/preview': {
      id: '/portfolio_/preview'
      path: '/portfolio/preview'
      fullPath: '/portfolio/preview'
      preLoaderRoute: typeof PortfolioPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-match_/preview': {
      id: '/job-match_/preview'
      path: '/job-match/preview'
      fullPath: '/job-match/preview'
      preLoaderRoute: typeof JobMatchPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview_/preview': {
      id: '/interview_/preview'
      path: '/interview/preview'
      fullPath: '/interview/preview'
      preLoaderRoute: typeof InterviewPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter_/preview': {
      id: '/cover-letter_/preview'
      path: '/cover-letter/preview'
      fullPath: '/cover-letter/preview'
      preLoaderRoute: typeof CoverLetterPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career_/preview': {
      id: '/career_/preview'
      path: '/career/preview'
      fullPath: '/career/preview'
      preLoaderRoute: typeof CareerPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume_/result/$historyId': {
      id: '/resume_/result/$historyId'
      path: '/resume/result/$historyId'
      fullPath: '/resume/result/$historyId'
      preLoaderRoute: typeof ResumeResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/result/$historyId': {
      id: '/portfolio_/result/$historyId'
      path: '/portfolio/result/$historyId'
      fullPath: '/portfolio/result/$historyId'
      preLoaderRoute: typeof PortfolioResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-match_/result/$historyId': {
      id: '/job-match_/result/$historyId'
      path: '/job-match/result/$historyId'
      fullPath: '/job-match/result/$historyId'
      preLoaderRoute: typeof JobMatchResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview_/result/$historyId': {
      id: '/interview_/result/$historyId'
      path: '/interview/result/$historyId'
      fullPath: '/interview/result/$historyId'
      preLoaderRoute: typeof InterviewResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter_/result/$historyId': {
      id: '/cover-letter_/result/$historyId'
      path: '/cover-letter/result/$historyId'
      fullPath: '/cover-letter/result/$historyId'
      preLoaderRoute: typeof CoverLetterResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career_/result/$historyId': {
      id: '/career_/result/$historyId'
      path: '/career/result/$historyId'
      fullPath: '/career/result/$historyId'
      preLoaderRoute: typeof CareerResultHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CareerRoute: CareerRoute,
  CoverLetterRoute: CoverLetterRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  InterviewRoute: InterviewRoute,
  JobMatchRoute: JobMatchRoute,
  LandingClassicRoute: LandingClassicRoute,
  LandingExperimentRoute: LandingExperimentRoute,
  LandingToolsRoute: LandingToolsRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CareerPreviewRoute: CareerPreviewRoute,
  CoverLetterPreviewRoute: CoverLetterPreviewRoute,
  InterviewPreviewRoute: InterviewPreviewRoute,
  JobMatchPreviewRoute: JobMatchPreviewRoute,
  PortfolioPreviewRoute: PortfolioPreviewRoute,
  ResumePreviewRoute: ResumePreviewRoute,
  CareerResultHistoryIdRoute: CareerResultHistoryIdRoute,
  CoverLetterResultHistoryIdRoute: CoverLetterResultHistoryIdRoute,
  InterviewResultHistoryIdRoute: InterviewResultHistoryIdRoute,
  JobMatchResultHistoryIdRoute: JobMatchResultHistoryIdRoute,
  PortfolioResultHistoryIdRoute: PortfolioResultHistoryIdRoute,
  ResumeResultHistoryIdRoute: ResumeResultHistoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
