import type { LucideIcon } from 'lucide-react'
import { PanelsTopLeft } from 'lucide-react'
import { getNavDestination } from '#/lib/navigation/navGroups'
import { getToolByHistoryName } from '#/lib/tools/registry'

/**
 * How a saved run's `tool_name` is shown in lists (dashboard Recent/Starred and
 * History). Registry tools use their own label, icon and accent; the two
 * backend-only families below get a friendly name instead of the raw tag.
 *
 * `application-drafts` mirrors backend `DRAFTS_TOOL_NAME`
 * (backend/app/services/application_drafts.py); it is generated by the
 * Applications prepare step and is not a browser tool id (see the note on
 * BROWSER_TOOL_IDS in lib/telemetry/client.ts).
 */
export const APPLICATION_DRAFTS_TOOL_NAME = 'application-drafts'
const CV_STUDIO_TOOL_NAMES = new Set(['cv-quality', 'cv-tailoring'])

export type HistoryToolKind = 'tool' | 'application-drafts' | 'cv-studio' | 'unknown'

export type HistoryToolDisplay = {
  kind: HistoryToolKind
  label: string
  icon: LucideIcon
  accent?: string
  /** Result route template for registry tools (`$historyId` placeholder). */
  route?: string
}

function humanize(toolName: string) {
  const text = toolName.replace(/[-_]+/g, ' ').trim()
  if (!text) return 'Saved run'
  return text.charAt(0).toUpperCase() + text.slice(1).toLowerCase()
}

export function historyToolDisplay(toolName: string): HistoryToolDisplay {
  const tool = getToolByHistoryName(toolName)
  if (tool) {
    return {
      kind: 'tool',
      label: tool.shortLabel,
      icon: tool.icon,
      accent: tool.accent,
      route: tool.resultRoute,
    }
  }
  if (toolName === APPLICATION_DRAFTS_TOOL_NAME) {
    return {
      kind: 'application-drafts',
      label: 'Application',
      icon: getNavDestination('/campaigns').icon,
    }
  }
  if (CV_STUDIO_TOOL_NAMES.has(toolName)) {
    return { kind: 'cv-studio', label: 'CV Studio', icon: PanelsTopLeft, accent: 'var(--accent)' }
  }
  return { kind: 'unknown', label: humanize(toolName), icon: getNavDestination('/history').icon }
}

/**
 * Where "Open" should go for a saved run, or null when no page can open it.
 * Older CV Studio checks have no result page (#362); application drafts open
 * their application (an application id is its workspace id — the backend's
 * Application is the Workspace row), falling back to the Applications board.
 */
export function historyRunHref(item: {
  id: string
  tool_name: string
  workspace?: { id: string } | null
}): string | null {
  const display = historyToolDisplay(item.tool_name)
  if (display.kind === 'tool' && display.route) return display.route.replace('$historyId', item.id)
  if (display.kind === 'application-drafts') {
    return item.workspace?.id ? `/campaigns/${item.workspace.id}` : '/campaigns'
  }
  return null
}
