/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobMatchRouteImport } from './routes/job-match'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ResumeResultHistoryIdRouteImport } from './routes/resume.result.$historyId'
import { Route as PortfolioResultHistoryIdRouteImport } from './routes/portfolio.result.$historyId'
import { Route as JobMatchResultHistoryIdRouteImport } from './routes/job-match.result.$historyId'
import { Route as InterviewResultHistoryIdRouteImport } from './routes/interview.result.$historyId'
import { Route as CoverLetterResultHistoryIdRouteImport } from './routes/cover-letter.result.$historyId'
import { Route as CareerResultHistoryIdRouteImport } from './routes/career.result.$historyId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchRoute = JobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeResultHistoryIdRoute = ResumeResultHistoryIdRouteImport.update({
  id: '/result/$historyId',
  path: '/result/$historyId',
  getParentRoute: () => ResumeRoute,
} as any)
const PortfolioResultHistoryIdRoute =
  PortfolioResultHistoryIdRouteImport.update({
    id: '/result/$historyId',
    path: '/result/$historyId',
    getParentRoute: () => PortfolioRoute,
  } as any)
const JobMatchResultHistoryIdRoute = JobMatchResultHistoryIdRouteImport.update({
  id: '/result/$historyId',
  path: '/result/$historyId',
  getParentRoute: () => JobMatchRoute,
} as any)
const InterviewResultHistoryIdRoute =
  InterviewResultHistoryIdRouteImport.update({
    id: '/result/$historyId',
    path: '/result/$historyId',
    getParentRoute: () => InterviewRoute,
  } as any)
const CoverLetterResultHistoryIdRoute =
  CoverLetterResultHistoryIdRouteImport.update({
    id: '/result/$historyId',
    path: '/result/$historyId',
    getParentRoute: () => CoverLetterRoute,
  } as any)
const CareerResultHistoryIdRoute = CareerResultHistoryIdRouteImport.update({
  id: '/result/$historyId',
  path: '/result/$historyId',
  getParentRoute: () => CareerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/career': typeof CareerRouteWithChildren
  '/cover-letter': typeof CoverLetterRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRouteWithChildren
  '/job-match': typeof JobMatchRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/resume': typeof ResumeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/career/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/career': typeof CareerRouteWithChildren
  '/cover-letter': typeof CoverLetterRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRouteWithChildren
  '/job-match': typeof JobMatchRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/resume': typeof ResumeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/career/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/career': typeof CareerRouteWithChildren
  '/cover-letter': typeof CoverLetterRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRouteWithChildren
  '/job-match': typeof JobMatchRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/resume': typeof ResumeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/career/result/$historyId': typeof CareerResultHistoryIdRoute
  '/cover-letter/result/$historyId': typeof CoverLetterResultHistoryIdRoute
  '/interview/result/$historyId': typeof InterviewResultHistoryIdRoute
  '/job-match/result/$historyId': typeof JobMatchResultHistoryIdRoute
  '/portfolio/result/$historyId': typeof PortfolioResultHistoryIdRoute
  '/resume/result/$historyId': typeof ResumeResultHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/login'
    | '/portfolio'
    | '/resume'
    | '/settings'
    | '/auth/callback'
    | '/career/result/$historyId'
    | '/cover-letter/result/$historyId'
    | '/interview/result/$historyId'
    | '/job-match/result/$historyId'
    | '/portfolio/result/$historyId'
    | '/resume/result/$historyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/login'
    | '/portfolio'
    | '/resume'
    | '/settings'
    | '/auth/callback'
    | '/career/result/$historyId'
    | '/cover-letter/result/$historyId'
    | '/interview/result/$historyId'
    | '/job-match/result/$historyId'
    | '/portfolio/result/$historyId'
    | '/resume/result/$historyId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/career'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-match'
    | '/login'
    | '/portfolio'
    | '/resume'
    | '/settings'
    | '/auth/callback'
    | '/career/result/$historyId'
    | '/cover-letter/result/$historyId'
    | '/interview/result/$historyId'
    | '/job-match/result/$historyId'
    | '/portfolio/result/$historyId'
    | '/resume/result/$historyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CareerRoute: typeof CareerRouteWithChildren
  CoverLetterRoute: typeof CoverLetterRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  InterviewRoute: typeof InterviewRouteWithChildren
  JobMatchRoute: typeof JobMatchRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ResumeRoute: typeof ResumeRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-match': {
      id: '/job-match'
      path: '/job-match'
      fullPath: '/job-match'
      preLoaderRoute: typeof JobMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/result/$historyId': {
      id: '/resume/result/$historyId'
      path: '/result/$historyId'
      fullPath: '/resume/result/$historyId'
      preLoaderRoute: typeof ResumeResultHistoryIdRouteImport
      parentRoute: typeof ResumeRoute
    }
    '/portfolio/result/$historyId': {
      id: '/portfolio/result/$historyId'
      path: '/result/$historyId'
      fullPath: '/portfolio/result/$historyId'
      preLoaderRoute: typeof PortfolioResultHistoryIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/job-match/result/$historyId': {
      id: '/job-match/result/$historyId'
      path: '/result/$historyId'
      fullPath: '/job-match/result/$historyId'
      preLoaderRoute: typeof JobMatchResultHistoryIdRouteImport
      parentRoute: typeof JobMatchRoute
    }
    '/interview/result/$historyId': {
      id: '/interview/result/$historyId'
      path: '/result/$historyId'
      fullPath: '/interview/result/$historyId'
      preLoaderRoute: typeof InterviewResultHistoryIdRouteImport
      parentRoute: typeof InterviewRoute
    }
    '/cover-letter/result/$historyId': {
      id: '/cover-letter/result/$historyId'
      path: '/result/$historyId'
      fullPath: '/cover-letter/result/$historyId'
      preLoaderRoute: typeof CoverLetterResultHistoryIdRouteImport
      parentRoute: typeof CoverLetterRoute
    }
    '/career/result/$historyId': {
      id: '/career/result/$historyId'
      path: '/result/$historyId'
      fullPath: '/career/result/$historyId'
      preLoaderRoute: typeof CareerResultHistoryIdRouteImport
      parentRoute: typeof CareerRoute
    }
  }
}

interface CareerRouteChildren {
  CareerResultHistoryIdRoute: typeof CareerResultHistoryIdRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerResultHistoryIdRoute: CareerResultHistoryIdRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface CoverLetterRouteChildren {
  CoverLetterResultHistoryIdRoute: typeof CoverLetterResultHistoryIdRoute
}

const CoverLetterRouteChildren: CoverLetterRouteChildren = {
  CoverLetterResultHistoryIdRoute: CoverLetterResultHistoryIdRoute,
}

const CoverLetterRouteWithChildren = CoverLetterRoute._addFileChildren(
  CoverLetterRouteChildren,
)

interface InterviewRouteChildren {
  InterviewResultHistoryIdRoute: typeof InterviewResultHistoryIdRoute
}

const InterviewRouteChildren: InterviewRouteChildren = {
  InterviewResultHistoryIdRoute: InterviewResultHistoryIdRoute,
}

const InterviewRouteWithChildren = InterviewRoute._addFileChildren(
  InterviewRouteChildren,
)

interface JobMatchRouteChildren {
  JobMatchResultHistoryIdRoute: typeof JobMatchResultHistoryIdRoute
}

const JobMatchRouteChildren: JobMatchRouteChildren = {
  JobMatchResultHistoryIdRoute: JobMatchResultHistoryIdRoute,
}

const JobMatchRouteWithChildren = JobMatchRoute._addFileChildren(
  JobMatchRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioResultHistoryIdRoute: typeof PortfolioResultHistoryIdRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioResultHistoryIdRoute: PortfolioResultHistoryIdRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ResumeRouteChildren {
  ResumeResultHistoryIdRoute: typeof ResumeResultHistoryIdRoute
}

const ResumeRouteChildren: ResumeRouteChildren = {
  ResumeResultHistoryIdRoute: ResumeResultHistoryIdRoute,
}

const ResumeRouteWithChildren =
  ResumeRoute._addFileChildren(ResumeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CareerRoute: CareerRouteWithChildren,
  CoverLetterRoute: CoverLetterRouteWithChildren,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  InterviewRoute: InterviewRouteWithChildren,
  JobMatchRoute: JobMatchRouteWithChildren,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ResumeRoute: ResumeRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
